overblog_graphql:
    definitions:
        schema:
            query: Query
#            mutation: Mutation
        mappings:
            auto_discover: true

            types:
                - type: attribute
                  dir: '%kernel.project_dir%/src/Infrastructure/GraphQL'
                  suffix: null

overblog_graphiql:
    javascript_libraries:
        graphiql: "2.4.7"
        react: "17.0.2"
