framework:
    messenger:

        default_bus: query.bus
        buses:
            query.bus:
            command.bus:
            event.bus:

        transports:
            sync: 'sync://'

            events_sourcing:
                dsn: '%env(MESSENGER_EVENTS_SOURCING_DSN)%'

        routing:
            App\Domain\Event\EventInterface: events_sourcing
